# Constants....

PORT = 9090
ENCONDING_FORMAT = "utf-8"
RECV_BUFFER_SIZE = 1024
IP_SERVER = '127.0.0.1'
HELO = 'HELO'
DATA = 'DATA'
QUIT = 'QUIT'
GET = 'GET'
POST = 'POST'
HEAD = 'HEAD'
DELETE = 'DELETE'
